
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/db1?currentSchema=testdb1
    username: testdb1owner
    password: testdb1owner

  jpa:
    # show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      
    hibernate:
      ddl-auto: update


