package fr.an.sql;

import java.sql.BatchUpdateException;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLTimeoutException;
import java.sql.SQLWarning;
import java.sql.Wrapper;

public interface Statement extends Wrapper, AutoCloseable {
    void close()                               throws SQLException;
    boolean isClosed()                         throws SQLException;
    public void closeOnCompletion()            throws SQLException;
    public boolean isCloseOnCompletion()       throws SQLException;

    Connection getConnection()                 throws SQLException;

    void cancel()                              throws SQLException;
    
    ResultSet executeQuery(String sql)         throws SQLException;
    int executeUpdate(String sql)              throws SQLException;

    void addBatch( String sql )                throws SQLException;
    void clearBatch()                          throws SQLException;
    int[] executeBatch()                       throws SQLException;

    boolean execute(String sql)                throws SQLException;
    ResultSet getResultSet()                   throws SQLException;
    int getUpdateCount()                       throws SQLException;
    boolean getMoreResults()                   throws SQLException;
    boolean getMoreResults(int current)        throws SQLException;
    ResultSet getGeneratedKeys()               throws SQLException;

    // properties with Getter/Setter:
    // maxFieldSize, maxRows, queryTimeout, fetchDirection, poolable
    
    // properties with Getter only: 
    // resultSetConcurrency, resultSetType, ResultSetHoldability
    
    
    
    int getMaxFieldSize()                                           throws SQLException;
    void setMaxFieldSize(int max)                                           throws SQLException;

    int getMaxRows()                                           throws SQLException;
    void setMaxRows(int max)                                           throws SQLException;

    void setEscapeProcessing(boolean enable)                                           throws SQLException;

    int getQueryTimeout()                                           throws SQLException;
    void setQueryTimeout(int seconds)                                           throws SQLException;

    SQLWarning getWarnings()                                           throws SQLException;
    void clearWarnings()                                           throws SQLException;

    void setCursorName(String name)                                           throws SQLException;


    void setFetchDirection(int direction)                                           throws SQLException;
    int getFetchDirection()                                           throws SQLException;
    void setFetchSize(int rows)                                           throws SQLException;
    int getFetchSize()                                           throws SQLException;

    int getResultSetConcurrency()                                           throws SQLException;
    int getResultSetType()                                            throws SQLException;


    int executeUpdate(String sql, int autoGeneratedKeys)                                           throws SQLException;
    int executeUpdate(String sql, int columnIndexes[])                                           throws SQLException;
    int executeUpdate(String sql, String columnNames[])                                           throws SQLException;

    boolean execute(String sql, int autoGeneratedKeys)                                           throws SQLException;
    boolean execute(String sql, int columnIndexes[])                                           throws SQLException;
    boolean execute(String sql, String columnNames[])                                           throws SQLException;

    int getResultSetHoldability()                                           throws SQLException;

    void setPoolable(boolean poolable)                                           throws SQLException;
    boolean isPoolable()                                           throws SQLException;

    //--------------------------JDBC 4.1 -----------------------------


    default long getLargeUpdateCount()                                           throws SQLException { throw new UnsupportedOperationException("getLargeUpdateCount not implemented"); }
    default void setLargeMaxRows(long max)                                           throws SQLException { throw new UnsupportedOperationException("setLargeMaxRows not implemented"); }
    default long getLargeMaxRows()                                           throws SQLException { return 0; }
    default long[] executeLargeBatch()                                           throws SQLException { throw new UnsupportedOperationException("executeLargeBatch not implemented"); }
    default long executeLargeUpdate(String sql)                                           throws SQLException { throw new UnsupportedOperationException("executeLargeUpdate not implemented"); }
    default long executeLargeUpdate(String sql, int autoGeneratedKeys)                                           throws SQLException { throw new SQLFeatureNotSupportedException("executeLargeUpdate not implemented"); }
    default long executeLargeUpdate(String sql, int columnIndexes[])                                           throws SQLException { throw new SQLFeatureNotSupportedException("executeLargeUpdate not implemented"); }
    default long executeLargeUpdate(String sql, String columnNames[])                                           throws SQLException { throw new SQLFeatureNotSupportedException("executeLargeUpdate not implemented"); }
}
