package fr.an.test.eclipsemirror;

import java.io.File;

import org.apache.commons.io.FileUtils;
import org.junit.Assert;
import org.junit.Test;

public class SteganoEncodeMainTest {

    @Test
    public void testRun_test1() throws Exception {
        // Prepare
        // dir generated by corresponding SteganoEncodeMain test (copyed from "target/tests/test1" )
        File inputDir = new File("src");
        File outputDir = new File("target/tests/test1");
        if (outputDir.exists()) {
            FileUtils.deleteDirectory(outputDir);
        }
        outputDir.mkdirs();
        
        SteganoEncodeMain sut = new SteganoEncodeMain();
        sut.setInputDir(inputDir);
        // sut.setExtName(".png");
        sut.setMaxPartLen(10000);
        sut.setOutputDir(outputDir);
        sut.setOutputFilename("test1");
        // Perform
        sut.run();
        // Post-check
        Assert.assertEquals(5, outputDir.listFiles().length);
        Assert.assertTrue(new File(outputDir, "test1.html").exists());
        Assert.assertTrue(new File(outputDir, "test1-0.html").exists());
        Assert.assertTrue(new File(outputDir, "test1-0.png").exists());
        Assert.assertTrue(new File(outputDir, "test1-1.png").exists());
        Assert.assertTrue(new File(outputDir, "test1-2.png").exists());
    }

}
