/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ParquetPageEncodingStatsDTO { 
    count?: number;
    encoding?: ParquetPageEncodingStatsDTO.EncodingEnum;
    pageType?: ParquetPageEncodingStatsDTO.PageTypeEnum;
}
export namespace ParquetPageEncodingStatsDTO {
    export type EncodingEnum = 'PLAIN' | 'PLAIN_DICTIONARY' | 'RLE' | 'BIT_PACKED' | 'DELTA_BINARY_PACKED' | 'DELTA_LENGTH_BYTE_ARRAY' | 'DELTA_BYTE_ARRAY' | 'RLE_DICTIONARY' | 'BYTE_STREAM_SPLIT';
    export const EncodingEnum = {
        PLAIN: 'PLAIN' as EncodingEnum,
        PLAINDICTIONARY: 'PLAIN_DICTIONARY' as EncodingEnum,
        RLE: 'RLE' as EncodingEnum,
        BITPACKED: 'BIT_PACKED' as EncodingEnum,
        DELTABINARYPACKED: 'DELTA_BINARY_PACKED' as EncodingEnum,
        DELTALENGTHBYTEARRAY: 'DELTA_LENGTH_BYTE_ARRAY' as EncodingEnum,
        DELTABYTEARRAY: 'DELTA_BYTE_ARRAY' as EncodingEnum,
        RLEDICTIONARY: 'RLE_DICTIONARY' as EncodingEnum,
        BYTESTREAMSPLIT: 'BYTE_STREAM_SPLIT' as EncodingEnum
    };
    export type PageTypeEnum = 'DATA_PAGE' | 'INDEX_PAGE' | 'DICTIONARY_PAGE' | 'DATA_PAGE_V2';
    export const PageTypeEnum = {
        DATAPAGE: 'DATA_PAGE' as PageTypeEnum,
        INDEXPAGE: 'INDEX_PAGE' as PageTypeEnum,
        DICTIONARYPAGE: 'DICTIONARY_PAGE' as PageTypeEnum,
        DATAPAGEV2: 'DATA_PAGE_V2' as PageTypeEnum
    };
}
