/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParquetAesGcmCtrV1 } from './parquetAesGcmCtrV1';
import { ParquetAesGcmV1 } from './parquetAesGcmV1';

export interface ParquetEncryptionAlgorithmDTO { 
    aesgcmv1?: ParquetAesGcmV1;
    aesgcmctrv1?: ParquetAesGcmCtrV1;
}