/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParquetColumnChunkMetaDataDTO } from './parquetColumnChunkMetaDataDTO';
import { ParquetColumnCryptoMetaDataDTO } from './parquetColumnCryptoMetaDataDTO';


export interface ParquetColumnChunkDTO { 
    colIndexLength?: number;
    colIndexOffset?: number;
    colName?: string;
    cryptoMetadata?: ParquetColumnCryptoMetaDataDTO;
    encryptedColMetadata?: string;
    fileOffset?: number;
    filePath?: string;
    metaData?: ParquetColumnChunkMetaDataDTO;
    offsetIndexLength?: number;
    offsetIndexOffset?: number;
}
