/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParquetBlockMetadataDTO } from './parquetBlockMetadataDTO';
import { ParquetEncryptionAlgorithmDTO } from './parquetEncryptionAlgorithmDTO';
import { ParquetSchemaElementDTO } from './parquetSchemaElementDTO';

export interface ParquetFileInfoDTO { 
    version?: number;
    schema?: Array<ParquetSchemaElementDTO>;
    numRows?: number;
    blocks?: Array<ParquetBlockMetadataDTO>;
    keyValueMetadata?: { [key: string]: string; };
    createdBy?: string;
    encryptionAlgorithm?: ParquetEncryptionAlgorithmDTO;
    footerSigningKeyMetadata?: Array<string>;
}