/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParquetColumnOrderDTO } from './parquetColumnOrderDTO';
import { ParquetEncryptionAlgorithmDTO } from './parquetEncryptionAlgorithmDTO';
import { ParquetRowGroupDTO } from './parquetRowGroupDTO';
import { ParquetSchemaElementDTO } from './parquetSchemaElementDTO';


export interface ParquetFileInfoDTO { 
    colOrders?: Array<ParquetColumnOrderDTO>;
    createdBy?: string;
    encryptionAlgorithm?: ParquetEncryptionAlgorithmDTO;
    footerSigningKeyMetadata?: string;
    keyValueMetadata?: { [key: string]: string; };
    numRows?: number;
    rowGroups?: Array<ParquetRowGroupDTO>;
    schema: Array<ParquetSchemaElementDTO>;
    version?: number;
}
