/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BinaryParquetStatisticsDTO } from './binaryParquetStatisticsDTO';
import { BooleanParquetStatisticsDTO } from './booleanParquetStatisticsDTO';
import { DoubleParquetStatisticsDTO } from './doubleParquetStatisticsDTO';
import { FloatParquetStatisticsDTO } from './floatParquetStatisticsDTO';
import { IntParquetStatisticsDTO } from './intParquetStatisticsDTO';
import { LongParquetStatisticsDTO } from './longParquetStatisticsDTO';
import { ParquetColumnChunkPropertiesDTO } from './parquetColumnChunkPropertiesDTO';
import { ParquetEncodingStatsDTO } from './parquetEncodingStatsDTO';
import { ParquetIndexReferenceDTO } from './parquetIndexReferenceDTO';
import { StringParquetStatisticsDTO } from './stringParquetStatisticsDTO';

export interface ParquetColumnChunkMetaDataDTO {
    rowGroupOrdinal?: number;
    encodingStats?: ParquetEncodingStatsDTO;
    properties?: ParquetColumnChunkPropertiesDTO;
    columnIndexReference?: ParquetIndexReferenceDTO;
    offsetIndexReference?: ParquetIndexReferenceDTO;
    bloomFilterOffset?: number;
    firstDataPageOffset?: number;
    dictionaryPageOffset?: number;
    valueCount?: number;
    totalSize?: number;
    totalUncompressedSize?: number;
    statistics?: BinaryParquetStatisticsDTO | BooleanParquetStatisticsDTO | DoubleParquetStatisticsDTO | FloatParquetStatisticsDTO | IntParquetStatisticsDTO | LongParquetStatisticsDTO | StringParquetStatisticsDTO;
}
