/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParquetColumnChunkDTO } from './parquetColumnChunkDTO';
import { ParquetSortingColumnDTO } from './parquetSortingColumnDTO';


export interface ParquetRowGroupDTO { 
    columns?: Array<ParquetColumnChunkDTO>;
    fileOffset?: number;
    numRows?: number;
    ordinal?: number;
    sortingColumns?: Array<ParquetSortingColumnDTO>;
    totalByteSize?: number;
    totalCompressedSize?: number;
}
