/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ParquetColumnChunkPropertiesDTO { 
    codec?: ParquetColumnChunkPropertiesDTO.CodecEnum;
    path?: string;
    encodings?: Array<ParquetColumnChunkPropertiesDTO.EncodingsEnum>;
}
export namespace ParquetColumnChunkPropertiesDTO {
    export type CodecEnum = 'UNCOMPRESSED' | 'SNAPPY' | 'GZIP' | 'LZO' | 'BROTLI' | 'LZ4' | 'ZSTD' | 'LZ4_RAW';
    export const CodecEnum = {
        UNCOMPRESSED: 'UNCOMPRESSED' as CodecEnum,
        SNAPPY: 'SNAPPY' as CodecEnum,
        GZIP: 'GZIP' as CodecEnum,
        LZO: 'LZO' as CodecEnum,
        BROTLI: 'BROTLI' as CodecEnum,
        LZ4: 'LZ4' as CodecEnum,
        ZSTD: 'ZSTD' as CodecEnum,
        LZ4RAW: 'LZ4_RAW' as CodecEnum
    };
    export type EncodingsEnum = 'PLAIN' | 'PLAIN_DICTIONARY' | 'RLE' | 'BIT_PACKED' | 'DELTA_BINARY_PACKED' | 'DELTA_LENGTH_BYTE_ARRAY' | 'DELTA_BYTE_ARRAY' | 'RLE_DICTIONARY' | 'BYTE_STREAM_SPLIT';
    export const EncodingsEnum = {
        PLAIN: 'PLAIN' as EncodingsEnum,
        PLAINDICTIONARY: 'PLAIN_DICTIONARY' as EncodingsEnum,
        RLE: 'RLE' as EncodingsEnum,
        BITPACKED: 'BIT_PACKED' as EncodingsEnum,
        DELTABINARYPACKED: 'DELTA_BINARY_PACKED' as EncodingsEnum,
        DELTALENGTHBYTEARRAY: 'DELTA_LENGTH_BYTE_ARRAY' as EncodingsEnum,
        DELTABYTEARRAY: 'DELTA_BYTE_ARRAY' as EncodingsEnum,
        RLEDICTIONARY: 'RLE_DICTIONARY' as EncodingsEnum,
        BYTESTREAMSPLIT: 'BYTE_STREAM_SPLIT' as EncodingsEnum
    };
}