/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParquetPageEncodingStatsDTO } from './parquetPageEncodingStatsDTO';
import { ParquetStatisticsDTOobject } from './parquetStatisticsDTOobject';


export interface ParquetColumnChunkMetaDataDTO { 
    bloomFilterOffset?: number;
    dataPageOffset?: number;
    dicPageOffset?: number;
    encodingStats?: Array<ParquetPageEncodingStatsDTO>;
    indexPageOffset?: number;
    keyValueMetadata?: { [key: string]: string; };
    numValues?: number;
    statistics?: ParquetStatisticsDTOobject;
    totalCompressedSize?: number;
    totalUncompressedSize?: number;
}
