/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParquetAesGcmCtrV1 } from './parquetAesGcmCtrV1';
import { ParquetAesGcmV1 } from './parquetAesGcmV1';


export interface ParquetEncryptionAlgorithmDTO { 
    aesGCMCTRV1?: ParquetAesGcmCtrV1;
    aesGCMV1?: ParquetAesGcmV1;
}
