/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ParquetLogicalType { 
    typeEnum?: ParquetLogicalType.TypeEnumEnum;
}
export namespace ParquetLogicalType {
    export type TypeEnumEnum = 'STRING' | 'MAP' | 'LIST' | 'ENUM' | 'DECIMAL' | 'DATE' | 'TIME_NANOS' | 'TIME_MICROS' | 'TIME_MILLIS' | 'TIMESTAMP_NANOS' | 'TIMESTAMP_MICROS' | 'TIMESTAMP_MILLIS' | 'INTEGER' | 'UNKNOWN' | 'JSON' | 'BSON' | 'UUID' | 'NULL';
    export const TypeEnumEnum = {
        STRING: 'STRING' as TypeEnumEnum,
        MAP: 'MAP' as TypeEnumEnum,
        LIST: 'LIST' as TypeEnumEnum,
        ENUM: 'ENUM' as TypeEnumEnum,
        DECIMAL: 'DECIMAL' as TypeEnumEnum,
        DATE: 'DATE' as TypeEnumEnum,
        TIMENANOS: 'TIME_NANOS' as TypeEnumEnum,
        TIMEMICROS: 'TIME_MICROS' as TypeEnumEnum,
        TIMEMILLIS: 'TIME_MILLIS' as TypeEnumEnum,
        TIMESTAMPNANOS: 'TIMESTAMP_NANOS' as TypeEnumEnum,
        TIMESTAMPMICROS: 'TIMESTAMP_MICROS' as TypeEnumEnum,
        TIMESTAMPMILLIS: 'TIMESTAMP_MILLIS' as TypeEnumEnum,
        INTEGER: 'INTEGER' as TypeEnumEnum,
        UNKNOWN: 'UNKNOWN' as TypeEnumEnum,
        JSON: 'JSON' as TypeEnumEnum,
        BSON: 'BSON' as TypeEnumEnum,
        UUID: 'UUID' as TypeEnumEnum,
        NULL: 'NULL' as TypeEnumEnum
    };
}
