/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParquetSchemaElementDTO } from './parquetSchemaElementDTO';
import { PartitionAndFileDataInfoDTO } from './partitionAndFileDataInfoDTO';
import { PartitionScanStatisticsDTO } from './partitionScanStatisticsDTO';


export interface ScanDirFileMetadatasResultDTO { 
    baseDir?: string;
    partFileInfos?: Array<PartitionAndFileDataInfoDTO>;
    partitionScanStatistics?: Array<PartitionScanStatisticsDTO>;
    schema?: Array<ParquetSchemaElementDTO>;
}
