
app:
  atomix:
    memberId: node2
    hostname: localhost
    port: 8052
    bootstrapNodes:
      - memberId: node1
        hostname: localhost
        port: 8051
      - memberId: node2
        hostname: localhost
        port: 8052
      - memberId: node3
        hostname: localhost
        port: 8053

server:
  port: 8082