/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ParquetFileInfoDTO } from '../model/parquetFileInfoDTO';
import { ScanDirFileMetadatasResultDTO } from '../model/scanDirFileMetadatasResultDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ParquetMetadataRestControllerService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * readFileMetadata
     * 
     * @param file file
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public readFileMetadataUsingGET(file: string, observe?: 'body', reportProgress?: boolean): Observable<ParquetFileInfoDTO>;
    public readFileMetadataUsingGET(file: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ParquetFileInfoDTO>>;
    public readFileMetadataUsingGET(file: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ParquetFileInfoDTO>>;
    public readFileMetadataUsingGET(file: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (file === null || file === undefined) {
            throw new Error('Required parameter file was null or undefined when calling readFileMetadataUsingGET.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (file !== undefined && file !== null) {
            queryParameters = queryParameters.set('file', <any>file);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ParquetFileInfoDTO>(`${this.basePath}/api/parquet-metadata/readFileMetadata`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * scanDirFileMetadata
     * 
     * @param baseDir baseDir
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public scanDirFileMetadataUsingGET(baseDir: string, observe?: 'body', reportProgress?: boolean): Observable<ScanDirFileMetadatasResultDTO>;
    public scanDirFileMetadataUsingGET(baseDir: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ScanDirFileMetadatasResultDTO>>;
    public scanDirFileMetadataUsingGET(baseDir: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ScanDirFileMetadatasResultDTO>>;
    public scanDirFileMetadataUsingGET(baseDir: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (baseDir === null || baseDir === undefined) {
            throw new Error('Required parameter baseDir was null or undefined when calling scanDirFileMetadataUsingGET.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (baseDir !== undefined && baseDir !== null) {
            queryParameters = queryParameters.set('baseDir', <any>baseDir);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ScanDirFileMetadatasResultDTO>(`${this.basePath}/api/parquet-metadata/scanDirFileMetadata`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
