version: '2'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:5.0.1'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'confluentinc/cp-kafka:5.0.1'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
